Auto = read.table("Auto.txt")
View(Auto)
pairs(Auto)
names(Auto)
Auto = read.table("Auto.txt",header = T)
names(Auto)
Auto1 <- Auto[, 1:8]
View(Auto1)
cor(Auto1)
names(Auto)
lm.fit=lm(mpg~.-name,data=Auto)
attach(Auto)
summary(lm.fit)
f=lm(mpg~cylinders+displacement+horsepower+weight+acceleration+year+origin)
summary(f)
par(mfrow=c(2,2))
plot(f)
summary(lm(mpg~cylinders+displacement+horsepower+weight+acceleration:year+year+origin))
summary(lm(mpg~cylinders*displacement+horsepower+weight+acceleration+year+origin))
f=lm(mpg~.-name+I(cylinders)^2,data=Auto)
f=lm(mpg~.-name+I((cylinders)^2),data=Auto)
summary(f)
f=lm(mpg~.-name+I((year)^2),data = Auto)
summary(f)
