set.seed(1)
x <- rnorm(100)
eps <- rnorm(100, mean = 0, sd = sqrt(0.25))
y <- -1 + 0.5*x + eps
length(y)
plot(x,y)
f <- lm(y~x)
summary(f)
plot(x,y)
abline(f, col="red")
abline(-1, 0.5, col="black")
legend("bottomright", c("Least Sqaures", "Regression"), col=c("red", "black"), lty = c(1,1), title = "Legend")
poly <- lm(y~x + I(x^2))
summary(poly)
set.seed(1)
eps <- rnorm(100, mean = 0, sd = sqrt(0.1))
y <- -1 + 0.5 * x + eps
plot(x,y)
lessnoise <- lm(y~x)
summary(lessnoise)
abline(lessnoise, col = "green")
abline(-1, 0.5, col = "red")
legend("bottomright", c("Least Squares", "Regression"), col = c("green", "red"), lty = c(1,1))
set.seed(1)
eps <- rnorm(100, mean = 0, sd = sqrt(0.75))
y <- -1 + 0.5 * x + eps
plot(x,y)
morenoise <- lm(y~x)
summary(morenoise)
abline(morenoise, col = "blue")
abline(-1, 0.5, col = "orange")
legend("bottomright", c("Least Squares", "Regression"), col = c("blue", "orange"), lty = c(1,1))
confint(f)
confint(lessnoise)
confint(morenoise)
